{% set name = "PyLaTeX" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: 25d68aa0c7c10b1d6d95092933ffa3efeb84a57d614f68e12935985fbcdae85e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - ordered-set
    - python

test:
  imports:
    - pylatex

about:
  home: https://github.com/JelteF/PyLaTeX
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python library for creating LaTeX files and snippets
  doc_url: https://jeltef.github.io/PyLaTeX

extra:
  recipe-maintainers:
    - Hoxbro
