{% set name = "PyLaTeX" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: d3c12efb8b260771260443dce78d1e9089c09f9d0b92e6273dfca0bf5e7302fb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - ordered-set
    - python

test:
  imports:
    - pylatex

about:
  home: https://github.com/JelteF/PyLaTeX
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python library for creating LaTeX files and snippets
  doc_url: https://jeltef.github.io/PyLaTeX

extra:
  recipe-maintainers:
    - Hoxbro
